### ISSUE TITLE
Table 'chat_room_list' doesn't exist

### ISSUE THREAD

**Issue by vijayshukla30** [vahidhedayati/grails-wschat-plugin#24]
I am using grails-2.3.5 and tomcat:7.0.55. But I am using Database Migration Plugin to create table in database. So I am not able to create a table 'chat_room_list' doesn't exist. Here is my full logs:-

Table 'chat_room_list' doesn't exist. Stacktrace follows:
 com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'chat_room_list' doesn't exist
    at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
    at com.mysql.jdbc.Util.getInstance(Util.java:386)
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1053)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4096)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4028)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2490)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2651)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2734)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2155)
    at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2322)
    at org.grails.datastore.gorm.GormStaticApi.methodMissing(GormStaticApi.groovy:104)
    at grails.plugin.wschat.rooms.WsChatRoomService.$tt__returnRoom(WsChatRoomService.groovy:27)
    at grails.plugin.wschat.WsChatController.index(WsChatController.groovy:30)
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:195)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

Please help me. Thanks in advance

**Comment by vahidhedayati** [comment]
I presume you have fixed issue if you have closed it ?

**Comment by vijayshukla30** [comment]
Yes
